name: release Open VSX

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Release Open VSX
        run: |
          npx vsce package -o svn-scm-ovsx.vsix
          npx ovsx publish svn-scm-ovsx.vsix -p ${{ secrets.ovsxToken }}

      - name: Get tag
        id: getTag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Upload Open VSX to release
        uses: softprops/action-gh-release@v2
        with:
          files: svn-scm-ovsx.vsix
          tag_name: ${{ steps.getTag.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
